console.log("hello");
setTimeout(function(){
console.log("world0");
},000);
console.log("bye0");
setTimeout(function(){
console.log("world1");
},000);
console.log("bye1");
setTimeout(function(){
console.log("world2");
},000);
console.log("bye2");
setTimeout(function(){
console.log("world3");
},000);
console.log("bye3");
setTimeout(function(){
console.log("world4");
},000);
console.log("bye4");

